name: Run MongoDB Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install 'pandas'
      run: pip install pandas

    - name: Install 'pymongo'
      run: pip install pymongo

    - name: Run Python Script
      run: python3 mongodb_connection.py
